export const services = [
  { slug: "jasa-digital-marketing-360", title: "360 Digital Marketing", badge: "Full Solution", hero: "Strategi Digital Menyeluruh, Hasil Terukur", desc: "Aktivasi end-to-end mulai awareness hingga konversi. Satu tim, satu strategi, hasil nyata.", features: [{ title: "Strategy Blueprint", desc: "Riset pasar, audience persona, dan roadmap kampanye." },{ title: "Multi-Channel Activation", desc: "Eksekusi terintegrasi di sosial, search, video, dan offline." },{ title: "Performance Analytics", desc: "Dashboard real-time dan optimisasi mingguan." }], process: [{ step: "Discovery & Audit", desc: "Pemetaan brand, audiens, dan benchmark kompetitor." },{ step: "Strategy & Creative", desc: "Big idea, content pillar, dan media plan." },{ step: "Execution & Optimize", desc: "Eksekusi, monitoring, dan iterasi berkelanjutan." }] },
  { slug: "social-media-management", title: "Social Media Management", badge: "Top Choice", hero: "Kelola Media Sosial No.1 di Indonesia", desc: "Strategi konten, produksi kreatif, community management, ads, dan reporting dalam satu tim.", features: [{ title: "Konten Premium", desc: "Visual, copy, dan video yang konsisten dengan brand identity." },{ title: "Community Care", desc: "Respons cepat, moderasi, dan engagement berkualitas." },{ title: "Growth Analytics", desc: "Reporting bulanan dengan insight aksionabel." }], process: [{ step: "Analisis & Strategi", desc: "Audit channel, kompetitor, dan content pillar." },{ step: "Produksi & Posting", desc: "Konten siap tayang sesuai content calendar." },{ step: "Evaluasi & Optimasi", desc: "Insight bulanan untuk pertumbuhan berkelanjutan." }] },
  { slug: "digital-campaign", title: "Digital Campaign / Ads", badge: "Trending", hero: "Iklan Digital yang Menghasilkan", desc: "Kelola iklan di 6 platform utama dengan strategi, kreatif, dan optimasi performa berkelanjutan.", features: [{ title: "Multi-Platform", desc: "Meta, Google, TikTok, YouTube, LinkedIn, Marketplace." },{ title: "Creative Production", desc: "Asset iklan yang stop-the-scroll." },{ title: "ROAS-Focused", desc: "Optimisasi budget untuk return maksimum." }], process: [{ step: "Strategy", desc: "Audience research, funnel design, dan media plan." },{ step: "Launch", desc: "Setup pixel, tracking, dan kreatif." },{ step: "Optimize", desc: "A/B testing dan scaling berkelanjutan." }] },
  { slug: "jasa-seo", title: "SEO & Local SEO", hero: "Naikkan Website ke Peringkat 1 Google", desc: "Investasi jangka panjang untuk trafik organik berkualitas. Tools premium Ahrefs & SEMrush.", features: [{ title: "Technical SEO", desc: "Audit teknis, kecepatan, dan struktur." },{ title: "On-Page Optimization", desc: "Riset keyword, konten, dan meta." },{ title: "Off-Page & Backlink", desc: "Authority building yang aman dan natural." }], process: [{ step: "Audit Mendalam", desc: "Analisis website dan kompetitor." },{ step: "Implementasi", desc: "Optimisasi teknis, konten, dan link." },{ step: "Tracking & Report", desc: "Laporan ranking dan trafik bulanan." }] },
  { slug: "jasa-pembuatan-website", title: "Website Development", badge: "Best", hero: "Website yang Bekerja untuk Bisnismu", desc: "Modern, aman, mobile-friendly. Company profile, landing page, e-commerce, hingga custom apps.", features: [{ title: "Custom Design", desc: "Desain unik yang merepresentasikan brand-mu." },{ title: "Lightning Fast", desc: "Performa optimal, SEO-friendly, dan secure." },{ title: "Full Support", desc: "Maintenance dan support setelah live." }], process: [{ step: "Discovery", desc: "Workshop kebutuhan dan goals bisnis." },{ step: "Design & Build", desc: "Wireframe, UI, dan development modern." },{ step: "Launch & Maintain", desc: "Go live, monitoring, dan iterasi." }] },
  { slug: "branding", title: "Branding & Design", hero: "Identitas Brand yang Berkesan", desc: "Logo eksklusif dan sistem brand yang konsisten dari digital hingga offline.", features: [{ title: "Konsep Eksklusif", desc: "Beberapa konsep awal, tidak template." },{ title: "Brand Guideline", desc: "Color, typography, dan usage rules." },{ title: "Source Files", desc: "Format lengkap untuk semua kebutuhan." }], process: [{ step: "Brand Discovery", desc: "Eksplorasi nilai, audiens, dan tone." },{ step: "Konsep & Revisi", desc: "Beberapa arah desain dengan revisi terstruktur." },{ step: "Final & Handover", desc: "File final dan brand guideline." }] },
  { slug: "affiliate-marketing", title: "KOL & Affiliate Marketing", badge: "New", hero: "Influencer & Affiliate yang Tepat Sasaran", desc: "Hubungkan brand dengan Key Opinion Leaders dan program afiliasi sesuai target pasar.", features: [{ title: "Talent Matching", desc: "Pemilihan KOL berbasis data dan audience-fit." },{ title: "Campaign Management", desc: "Briefing, koordinasi, dan content review." },{ title: "Performance Tracking", desc: "Tracking link, kode unik, dan reporting." }], process: [{ step: "Brief & Match", desc: "Tentukan goals dan pilih talent terbaik." },{ step: "Execution", desc: "Briefing, produksi konten, dan publishing." },{ step: "Report & Scale", desc: "Evaluasi performa dan rencana lanjutan." }] },
  { slug: "commercial-photography", title: "Commercial Photography", hero: "Foto Produk Profesional #1 di Indonesia", desc: "Untuk e-commerce, katalog, dan media sosial. Studio lengkap dengan fotografer & model profesional.", features: [{ title: "Studio Premium", desc: "Equipment dan lighting standar industri." },{ title: "Variasi Konsep", desc: "Flatlay, lifestyle, model, hingga 360." },{ title: "Fast Turnaround", desc: "Hasil cepat tanpa kompromi kualitas." }], process: [{ step: "Pilih Paket", desc: "Pilih sesuai jumlah dan jenis foto." },{ step: "Kirim Produk", desc: "Brief dan kirim produk ke studio." },{ step: "Sesi & Hasil", desc: "Sesi foto, editing, dan delivery." }] },
  { slug: "video-production", title: "Video Production", hero: "Video yang Menggerakkan Audiens", desc: "Video animasi, konten sosial media, hingga TVC komersial untuk awareness, edukasi, dan konversi.", features: [{ title: "Video Animasi", desc: "Motion graphic 2D explainer." },{ title: "Video Sosmed", desc: "Short-form vertikal yang viral-ready." },{ title: "Video Komersial", desc: "Produksi standar broadcast." }], process: [{ step: "Pre-Production", desc: "Script, storyboard, dan casting." },{ step: "Production", desc: "Shooting / animasi profesional." },{ step: "Post-Production", desc: "Editing, color, sound, dan delivery." }] },
  { slug: "apps-development", title: "Apps Development", hero: "Aplikasi Custom yang Scalable", desc: "Web dan mobile apps untuk kebutuhan bisnis spesifik dari MVP hingga enterprise.", features: [{ title: "Modern Stack", desc: "React Native, Next.js, TypeScript." },{ title: "Scalable Architecture", desc: "Siap tumbuh seiring bisnis." },{ title: "End-to-End", desc: "Design, build, deploy, maintain." }], process: [{ step: "Discovery", desc: "User research dan technical scoping." },{ step: "Design & Build", desc: "UI/UX, development, dan QA." },{ step: "Launch & Iterate", desc: "Release, monitor, iterate." }] },
];

export const solutions = [
  { slug: "enterprise", title: "Enterprise / Brand", hero: "Solusi Digital Marketing untuk Enterprise & Brand", desc: "Strategi digital skala besar untuk korporasi dan brand nasional.", clients: ["OCBC NISP","Fujifilm Instax","Pertamina","Bank BRI","Denso","Auto2000"] },
  { slug: "healthcare", title: "Healthcare", hero: "Solusi Digital untuk Lembaga Kesehatan", desc: "Mitra digital untuk klinik, rumah sakit, dan komunitas kesehatan.", clients: ["Bunda Medik","RS Onkologi Surabaya","CitaSehat Foundation"] },
  { slug: "education", title: "Education", hero: "Mitra Digital untuk Institusi Pendidikan", desc: "Membantu sekolah, kampus, dan platform edukasi membangun presence digital.", clients: ["Binus School","Latis Education","Universitas Terbuka"] },
  { slug: "fnb", title: "F&B / Kuliner", hero: "Solusi Digital untuk Bisnis F&B & Kuliner", desc: "Strategi konten, fotografi produk, dan iklan performa untuk restoran dan kafe.", clients: ["Bara Caffe","Nav Karaoke"] },
  { slug: "government", title: "Government & Organisasi", hero: "Komunikasi Digital untuk Lembaga Pemerintah", desc: "Strategi komunikasi publik yang modern, transparan, dan terpercaya.", clients: ["Diskominfo Kota Depok","Komdigi"] },
  { slug: "retail", title: "Retail & Toko Online", hero: "Solusi Digital untuk Bisnis Retail", desc: "Tingkatkan penjualan online dan offline dengan strategi digital terintegrasi.", clients: ["Forte Coolpro","KAGUMI","Herbalenku"] },
];

export const testimonials = [
  { name: "Andre Wijaya", role: "Founder, Aliyonics", quote: "Tim GoSocial sangat strategis. Brand identity kami benar-benar terangkat dan terstruktur." },
  { name: "Dr. Sinta Hapsari", role: "Direktur, RS Happy Land", quote: "Awareness rumah sakit kami meningkat signifikan. Pendekatan konten mereka empatik dan profesional." },
  { name: "Riko Pranata", role: "Marketing Lead, TRIV", quote: "Konten crypto yang accessible. Komunitas kami tumbuh sehat dengan engagement berkualitas." },
];
